/**
 * Shared across 606 and 607. Source: "Tipo Id" / "Tipo Identificación" columns
 * in the official DGII "Herramienta de Envío" tools.
 */
export const TIPO_IDENTIFICACION = {
  "1": "RNC",
  "2": "CEDULA",
} as const;

export type TipoIdentificacion = keyof typeof TIPO_IDENTIFICACION;

/** Catálogos oficiales del Formato 606 de la DGII, también usados por la interfaz. */
export const TIPO_BIENES_SERVICIOS_606 = {
  "01": "GASTOS DE PERSONAL",
  "02": "GASTOS POR TRABAJOS, SUMINISTROS Y SERVICIOS",
  "03": "ARRENDAMIENTOS",
  "04": "GASTOS DE ACTIVOS FIJO",
  "05": "GASTOS DE REPRESENTACIÓN",
  "06": "OTRAS DEDUCCIONES ADMITIDAS",
  "07": "GASTOS FINANCIEROS",
  "08": "GASTOS EXTRAORDINARIOS",
  "09": "COMPRAS Y GASTOS QUE FORMARAN PARTE DEL COSTO DE VENTA",
  "10": "ADQUISICIONES DE ACTIVOS",
  "11": "GASTOS DE SEGUROS",
} as const;

export const FORMA_PAGO_606 = {
  "01": "EFECTIVO",
  "02": "CHEQUES / TRANSFERENCIAS / DEPÓSITO",
  "03": "TARJETA CRÉDITO / DÉBITO",
  "04": "COMPRA A CRÉDITO",
  "05": "PERMUTA",
  "06": "NOTA DE CRÉDITO",
  "07": "MIXTO",
} as const;

export const TIPO_RETENCION_ISR_606 = {
  "00": "NINGUNA",
  "01": "ALQUILERES",
  "02": "HONORARIOS POR SERVICIOS",
  "03": "OTRAS RENTAS",
  "04": "OTRAS RENTAS (RENTAS PRESUNTAS)",
  "05": "INTERESES PAGADOS A PERSONAS JURÍDICAS RESIDENTES",
  "06": "INTERESES PAGADOS A PERSONAS FÍSICAS RESIDENTES",
  "07": "RETENCIÓN POR PROVEEDORES DEL ESTADO",
  "08": "JUEGOS TELEFÓNICOS",
  "09": "RETENCIONES SUBSECTOR DE GANADERÍA DE CARNE BOVINA",
} as const;
